// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PeopleUpdater is an autogenerated mock type for the PeopleUpdater type
type PeopleUpdater struct {
	mock.Mock
}

// UpdatePeople provides a mock function with given fields: name, surname, patronym, gender, nationality, age, id
func (_m *PeopleUpdater) UpdatePeople(name string, surname string, patronym string, gender string, nationality string, age int, id int64) error {
	ret := _m.Called(name, surname, patronym, gender, nationality, age, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePeople")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, int, int64) error); ok {
		r0 = rf(name, surname, patronym, gender, nationality, age, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPeopleUpdater creates a new instance of PeopleUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPeopleUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *PeopleUpdater {
	mock := &PeopleUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
