// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PeopleDeleter is an autogenerated mock type for the PeopleDeleter type
type PeopleDeleter struct {
	mock.Mock
}

// DeletePeople provides a mock function with given fields: id
func (_m *PeopleDeleter) DeletePeople(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePeople")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPeopleDeleter creates a new instance of PeopleDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPeopleDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PeopleDeleter {
	mock := &PeopleDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
